#!/bin/sh

. /etc/rc.subr

name=adguard
rcvar=adguard_enable
load_rc_config ${name}

: ${adguard_enable:=NO}
: ${adguard_user:=root}
: ${adguard_group:=wheel}
: ${adguard_workdir:="/usr/local/adguard"}
: ${adguard_pidfile:="/var/run/adguard/adguard.pid"}
: ${adguard_logfile:="/var/log/adguard/adguard.log"}

pidfile=${adguard_pidfile}
logfile=${adguard_logfile}
workdir=${adguard_workdir}

command=/usr/sbin/daemon
procname="/root/AdGuardHome/AdGuardHome"
command_args="-f ${procname} --host 0.0.0.0 --port 3000 --pidfile ${pidfile} --logfile ${logfile} --work-dir ${workdir}"

start_precmd="${name}_prestart"

adguard_prestart()
{
	PATH=${PATH}:/usr/local/bin:/usr/local/sbin
	export LC_CTYPE="en_US.UTF-8"
	for dir in ${workdir} ${logfile%/*} ${pidfile%/*}; do
		if [ ! -d "${dir}" ]; then
				install -d -o ${adguard_user} -g ${adguard_group} ${dir}
		fi
	done
}

run_rc_command "$1"
