#!/bin/sh
#
# PROVIDE: adguard
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# adguard_enable (bool):        Set to NO by default.
#                       Set it to YES to enable it.

. /etc/rc.subr

name=adguard
rcvar=adguard_enable
load_rc_config ${name}

: ${adguard_enable:=NO}
: ${adguard_user:=root}
: ${adguard_group:=wheel}
: ${adguard_conf_dir="/usr/local/adguard"}
: ${adguard_pidfile:="/var/run/adguard/adguard.pid"}

pidfile=${adguard_pidfile}

start_precmd="${name}_prestart"
command=/usr/sbin/daemon
procname="/root/AdGuardHome/AdGuardHome"
command_args="-f ${procname} --pidfile ${pidfile}"

adguard_prestart()
{
	PATH=${PATH}:/usr/local/bin:/usr/local/sbin
	export LC_CTYPE="en_US.UTF-8"
	for dir in ${adguard_conf_dir} ${pidfile%/*}; do
		if [ ! -d "${dir}" ]; then
			install -d -o ${adguard_user} -g ${adguard_group} ${dir}
		fi
	done
}

run_rc_command "$1"
